name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: mcr.microsoft.com/windows/servercore:ltsc2019 as base

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --rm -t usd-build .
